### ISSUE TITLE
the trait bound ... is not satisfied

### ISSUE THREAD

**Issue by tkr-sh** [dioxus-community/dioxus-free-icons#37]
When trying to create a basic icon with this code:
```rs
#[component]
pub fn test() -> Element {
    rsx!(
        Icon {
            width: 30,
            height: 30,
            fill: "black",
            icon: IoMailOpen,
        }
    )
}
```
I get the following error:

```shell
error[E0277]: the trait bound `fn(IconProps<_>) -> std::option::Option<dioxus_core::nodes::VNode> {Icon::<_>}: dioxus::prelude::ComponentFunction<_, _>` is not satisfied
  --> src/main.rs:36:9
   |
35 | /     rsx!(
36 | |         Icon {
   | |         ^^^^ the trait `dioxus::prelude::ComponentFunction<_, _>` is not implemented for fn item `fn(IconProps<_>) -> std::option::Option<dioxus_core::nodes::VNode> {Icon::<_>}`
37 | |             width: 30,
38 | |             height: 30,
...  |
41 | |         }
42 | |     )
   | |_____- required by a bound introduced by this call
   |
   = help: the trait `dioxus::prelude::ComponentFunction<Rc<Cell<RouterConfig<Route>>>>` is implemented for `Route`
```

**Comment by marc2332** [comment]
Are you using Dioxus 0.5?

**Comment by tkr-sh** [comment]
@marc2332 yes!

**Comment by tkr-sh** [comment]
```toml
[package]
...

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = ["fullstack", "router"] }
dioxus-free-icons = { version = "0.8.3", features = ["feather"] }

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
```
